"""add products, product_images tables and cascade delete

Revision ID: a3cc81d87994
Revises: ba1ab04a2376
Create Date: 2026-07-02 09:01:31.447287

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "a3cc81d87994"
down_revision: Union[str, Sequence[str], None] = "ba1ab04a2376"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("size", sa.String(length=255), nullable=False),
        sa.Column("price", sa.Integer(), nullable=False),
        sa.Column("brand", sa.String(length=100), nullable=True),
        sa.Column(
            "category",
            sa.Enum("OUTER", "TOP", "BOTTOM", "SHOES", "ACCESSORY", name="category"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("ON_SALE", "SOLD_OUT", "HIDDEN", name="status"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "product_images",
        sa.Column("product_id", sa.String(length=26), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=False),
        sa.Column("order_number", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=26), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_images_product_id"),
        "product_images",
        ["product_id"],
        unique=False,
    )
    op.drop_constraint(
        op.f("refresh_tokens_user_id_fkey"), "refresh_tokens", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "refresh_tokens", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "refresh_tokens", type_="foreignkey")
    op.create_foreign_key(
        op.f("refresh_tokens_user_id_fkey"),
        "refresh_tokens",
        "users",
        ["user_id"],
        ["id"],
    )
    op.drop_index(op.f("ix_product_images_product_id"), table_name="product_images")
    op.drop_table("product_images")
    op.drop_table("products")
    # ### end Alembic commands ###
