"""add phone_number and address to users

Revision ID: e79951599d68
Revises: 104b8bb8cf88
Create Date: 2026-07-03 08:55:52.278959

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e79951599d68"
down_revision: Union[str, Sequence[str], None] = "104b8bb8cf88"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("address", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "address")
    # ### end Alembic commands ###
